GET http://localhost:3000/product

###
GET http://localhost:3000/product/6119d8e1b0602e3738a6f201
###
POST http://localhost:3000/product
Content-Type: application/json

{
    "title": "Product 3",
    "price": 4
}

###
PATCH http://localhost:3000/product/611a00dac0191c283c880b62
Content-Type: application/json

{
    "title": "Product updated",
    "price": 2000
}

###

DELETE  http://localhost:3000/product/611a00dac0191c283c880b62
